import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  {children}

  <footer className="mt-16 border-t border-gray-200 bg-white">
    <div className="max-w-7xl mx-auto px-6 py-10 grid grid-cols-1 md:grid-cols-4 gap-8">
      <div>
        <h2 className="text-xl font-semibold">
          राधारानी स्टोर
        </h2>
        <p className="text-sm text-gray-600 mt-3">
          Premium quality clothes at shop prices.
        </p>
      </div>

      <div>
        <h3 className="font-semibold mb-3">
          Quick Links
        </h3>

        <a
  href="/">
 <p className="text-sm text-gray-600">
          Home
        </p>

 
</a>
       
        <a href="/#categories">
   <p className="text-sm text-gray-600">
          Categories
        </p>
</a>
      <a
  href={`${typeof window !== "undefined" ? window.location.pathname : ""}?cart=open`}
>

  <p className="text-sm text-gray-600">
          Cart
        </p>
  
</a>
      
      </div>

      <div>
        <h3 className="font-semibold mb-3">
          Support
        </h3>

        <a
  href="https://wa.me/919509295882"
  target="_blank"
  rel="noopener noreferrer"
>
    <p className="text-sm text-gray-600">
          WhatsApp Support
        </p>
</a>
      
        <p className="text-sm text-gray-600">
          Secure Payments
        </p>
        <p className="text-sm text-gray-600">
          All India Delivery
        </p>
      </div>

      <div>
        <h3 className="font-semibold mb-3">
          Contact
        </h3>
        <p className="text-sm text-gray-600">
          +91 9509295882
        </p>
      </div>
    </div>



    <div className="border-t border-gray-100 py-4 text-center text-sm text-gray-500">

      <div className="bg-black text-white overflow-hidden">
  <div className="whitespace-nowrap py-2 animate-scroll-strip">
    Delivery charges are extra •
    Porter / Delhivery charges as per your area •
    Delivery charges are extra •
    Porter / Delhivery charges as per your area
  </div>
</div>
      © 2026 Radharani Collection
    </div>
  </footer>
</body>
    </html>
  );
}
